/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetopoo.view;

/**
 *
 * @author Mateus
 */
public class AjudaView extends javax.swing.JFrame {

    /**
     * Creates new form AjudaView
     */
    public AjudaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLineOne = new javax.swing.JLabel();
        lblLineTwo = new javax.swing.JLabel();
        lblLineFour = new javax.swing.JLabel();
        lblLineFive = new javax.swing.JLabel();
        lblLineSix = new javax.swing.JLabel();
        lblLineSeven = new javax.swing.JLabel();
        lblLineEight = new javax.swing.JLabel();
        lblLineNine = new javax.swing.JLabel();
        lblLineEleven = new javax.swing.JLabel();
        lblLineTwelve = new javax.swing.JLabel();
        lblLineTen = new javax.swing.JLabel();
        lblLineThree = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");
        setResizable(false);

        lblLineOne.setText("O formalizador de texto serve para deixar o texto que você escreveu mais formal.");

        lblLineTwo.setText("Ele pode ser dividido em níveis e dependendo do nivel o tipo de formalidade muda.");

        lblLineFour.setText("Se você escolher o nivel mais baixo, pouca coisa pode ser mudada, mudando apenas");

        lblLineFive.setText("o necessário.");

        lblLineSix.setText("Se você escolher o médio o nível de palavras mudadas seram maior dependendo do");

        lblLineSeven.setText("contexto.");

        lblLineEight.setText("Se você escolher o alto, o seu texto ficará o mais formal possivel. E cuidado, isso  ");

        lblLineNine.setText("pode acabar soando estranho a depender do seu uso.");

        lblLineEleven.setText("Para formalizar é so clicar digitar seu texto, escolher o nivel e clicar na palavra : ");

        lblLineTwelve.setText("Formalizar");

        lblLineTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLineTen.setForeground(new java.awt.Color(153, 0, 0));
        lblLineTen.setText("COMO FORMALIZAR");

        lblLineThree.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLineThree.setForeground(new java.awt.Color(153, 0, 0));
        lblLineThree.setText("TIPOS DE NÍVEIS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLineOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLineFour)
                    .addComponent(lblLineFive)
                    .addComponent(lblLineSix)
                    .addComponent(lblLineSeven)
                    .addComponent(lblLineEight)
                    .addComponent(lblLineNine)
                    .addComponent(lblLineEleven)
                    .addComponent(lblLineTwelve)
                    .addComponent(lblLineTwo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblLineTen)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblLineThree)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLineOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineThree)
                .addGap(7, 7, 7)
                .addComponent(lblLineFour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineFive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineSix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineSeven)
                .addGap(18, 18, 18)
                .addComponent(lblLineEight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineNine)
                .addGap(27, 27, 27)
                .addComponent(lblLineTen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLineEleven)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLineTwelve)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjudaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjudaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjudaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjudaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjudaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLineEight;
    private javax.swing.JLabel lblLineEleven;
    private javax.swing.JLabel lblLineFive;
    private javax.swing.JLabel lblLineFour;
    private javax.swing.JLabel lblLineNine;
    private javax.swing.JLabel lblLineOne;
    private javax.swing.JLabel lblLineSeven;
    private javax.swing.JLabel lblLineSix;
    private javax.swing.JLabel lblLineTen;
    private javax.swing.JLabel lblLineThree;
    private javax.swing.JLabel lblLineTwelve;
    private javax.swing.JLabel lblLineTwo;
    // End of variables declaration//GEN-END:variables
}
