/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetopoo.view;

import br.com.projetopoo.model.Nivel;
import br.com.projetopoo.model.Organizador;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus
 */
public class FormalizarView extends javax.swing.JFrame {

    /**
     * Creates new form FormalizarView
     */
    public FormalizarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormalizador = new javax.swing.JLabel();
        lblDigiteSeuTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaTexto = new javax.swing.JTextArea();
        btnFormalizar = new javax.swing.JButton();
        lblDigiteONivelDaFormalizacao = new javax.swing.JLabel();
        jcBaixo = new javax.swing.JCheckBox();
        jcMedio = new javax.swing.JCheckBox();
        jcAlto = new javax.swing.JCheckBox();
        lblAjuda = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblVoltar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ULTRA FORMALIZATION");
        setResizable(false);

        lblFormalizador.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFormalizador.setForeground(new java.awt.Color(153, 0, 0));
        lblFormalizador.setText("Formalizador");

        lblDigiteSeuTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDigiteSeuTexto.setForeground(new java.awt.Color(0, 0, 153));
        lblDigiteSeuTexto.setText("Digite seu texto: ");

        txaTexto.setColumns(20);
        txaTexto.setRows(5);
        jScrollPane1.setViewportView(txaTexto);

        btnFormalizar.setText("Formalizar");
        btnFormalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormalizarActionPerformed(evt);
            }
        });

        lblDigiteONivelDaFormalizacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDigiteONivelDaFormalizacao.setForeground(new java.awt.Color(0, 0, 153));
        lblDigiteONivelDaFormalizacao.setText("Digite o nível da formalização: ");

        jcBaixo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcBaixo.setText("Baixo");
        jcBaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBaixoActionPerformed(evt);
            }
        });

        jcMedio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcMedio.setText("Médio");
        jcMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMedioActionPerformed(evt);
            }
        });

        jcAlto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcAlto.setText("Alto");
        jcAlto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcAltoActionPerformed(evt);
            }
        });

        lblAjuda.setText("Ajuda");
        lblAjuda.setToolTipText("Ver ajuda");
        lblAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAjudaMouseClicked(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left_arrow.png"))); // NOI18N
        lblVoltar.setToolTipText("Voltar");
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDigiteONivelDaFormalizacao)
                                .addGap(18, 18, 18)
                                .addComponent(jcBaixo)
                                .addGap(18, 18, 18)
                                .addComponent(jcMedio)
                                .addGap(18, 18, 18)
                                .addComponent(jcAlto))
                            .addComponent(btnFormalizar)
                            .addComponent(lblDigiteSeuTexto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVoltar)
                                .addGap(201, 201, 201)
                                .addComponent(lblFormalizador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAjuda, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAjuda)
                        .addGap(5, 5, 5)
                        .addComponent(lblFormalizador))
                    .addComponent(lblVoltar))
                .addGap(27, 27, 27)
                .addComponent(lblDigiteSeuTexto)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDigiteONivelDaFormalizacao)
                    .addComponent(jcBaixo)
                    .addComponent(jcMedio)
                    .addComponent(jcAlto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnFormalizar))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(687, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAjudaMouseClicked
        AjudaView telaAjuda = new AjudaView();
        telaAjuda.setVisible(true);
    }//GEN-LAST:event_lblAjudaMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        FirstView telaFirst = new FirstView();
        telaFirst.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void jcBaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBaixoActionPerformed
        jcMedio.setSelected(false);
        jcAlto.setSelected(false);
    }//GEN-LAST:event_jcBaixoActionPerformed

    private void jcMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMedioActionPerformed
        jcBaixo.setSelected(false);
        jcAlto.setSelected(false);
    }//GEN-LAST:event_jcMedioActionPerformed

    private void jcAltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcAltoActionPerformed
        jcBaixo.setSelected(false);
        jcMedio.setSelected(false);
    }//GEN-LAST:event_jcAltoActionPerformed

    private void btnFormalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormalizarActionPerformed

        if((!jcBaixo.isSelected()) && (!jcMedio.isSelected()) && (!jcAlto.isSelected())){
            JOptionPane.showMessageDialog(null,"Selecione um nivel");
        }else if(jcBaixo.isSelected()){
            Organizador organizar = new Organizador(txaTexto.getText(), Nivel.BAIXO);
            if(organizar.getTexto().equals("")){
                JOptionPane.showMessageDialog(null, "Texto vazio, informe um texto");
            }else{
                organizar.separarPalavras();
                organizar.formalizar();
                txaTexto.setText(organizar.getTexto());
            }
        }else if(jcMedio.isSelected()){
             Organizador organizar = new Organizador(txaTexto.getText(), Nivel.MEDIO);
            if(organizar.getTexto().equals("")){
                JOptionPane.showMessageDialog(null, "Texto vazio, informe um texto");
            }else{
                organizar.separarPalavras();
                organizar.formalizar();
                txaTexto.setText(organizar.getTexto());
            }
        }else{
            Organizador organizar = new Organizador(txaTexto.getText(), Nivel.ALTO);
            if(organizar.getTexto().equals("")){
                JOptionPane.showMessageDialog(null, "Texto vazio, informe um texto");
            }else{
                organizar.separarPalavras();
                organizar.formalizar();
                txaTexto.setText(organizar.getTexto());
            }
        }
    }//GEN-LAST:event_btnFormalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormalizarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormalizarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormalizar;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcAlto;
    private javax.swing.JCheckBox jcBaixo;
    private javax.swing.JCheckBox jcMedio;
    private javax.swing.JLabel lblAjuda;
    private javax.swing.JLabel lblDigiteONivelDaFormalizacao;
    private javax.swing.JLabel lblDigiteSeuTexto;
    private javax.swing.JLabel lblFormalizador;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTextArea txaTexto;
    // End of variables declaration//GEN-END:variables

    private static class JoptionPane {

        public JoptionPane() {
        }
    }
}
